post_install () {
  VBoxManage extpack install \
    --accept-license="$(sha256sum /usr/share/licenses/virtualbox-extension/PUEL | head --bytes=64)" \
    "/usr/share/virtualbox/extensions/Oracle_VirtualBox_Extension_Pack-${1%%-*}.vbox-extpack" >/dev/null
}

pre_upgrade() {
  post_remove "$@"
}

post_upgrade() {
  post_install "$@"
}

post_remove() {
  VBoxManage extpack uninstall 'Oracle VirtualBox Extension Pack' >/dev/null
}
