rebuild_module_dependencies() {
        EXTRAMODULES='extramodules-3.9-ARCH'
        depmod $(cat /lib/modules/$EXTRAMODULES/version)
}

post_install() {
  rebuild_module_dependencies
        echo
        echo 'For more information on this driver, see:'
        echo 'http://www.linuxfoundation.org/collaborate/workgroups/networking/alx'
}
post_upgrade() {
        rebuild_module_dependencies
}

post_remove() {
        rebuild_module_dependencies
}
