# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# compile CXX with /usr/bin/c++
CXX_FLAGS = -march=native -Ofast -pipe -fdiagnostics-color=always -fno-plt -O3 -DNDEBUG -fPIC   -pthread -std=c++11

CXX_DEFINES = -DOPENVDB_ABI_VERSION_NUMBER=6 -DOPENVDB_PRIVATE -DOPENVDB_TOOLS_RAYTRACER_USE_EXR -DOPENVDB_USE_BLOSC -Dopenvdb_shared_EXPORTS

CXX_INCLUDES = -I/build/openvdb-git/src/openvdb-6.1.0/openvdb/.. -I/build/openvdb-git/src/openvdb-6.1.0/openvdb/. -isystem /usr/include/OpenEXR/.. -isystem /usr/include/OpenEXR 

